/* Generated By:JavaCC: Do not edit this line. ModifiedRegexParserConstants.java */
package gramatics;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ModifiedRegexParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CHAR = 1;
  /** RegularExpression Id. */
  int ALTERNATIVE = 2;
  /** RegularExpression Id. */
  int LEFTROUNDCLOSER = 3;
  /** RegularExpression Id. */
  int RIGHTROUNDCLOSER = 4;
  /** RegularExpression Id. */
  int LEFTSQUARECLOSER = 5;
  /** RegularExpression Id. */
  int RIGHTSQUARECLOSER = 6;
  /** RegularExpression Id. */
  int LEFTCURLYCLOSER = 7;
  /** RegularExpression Id. */
  int RIGHTCURLYCLOSER = 8;
  /** RegularExpression Id. */
  int EOL = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<CHAR>",
    "\"|\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"\\n\"",
  };

}
